language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.4

jobs:
  include:
    - php: 7.4
      env:
        - COMPOSER_FLAGS="--prefer-lowest --prefer-stable"

    - php: 7.4
      env:
        - COVERAGE="--coverage-clover build/logs/clover.xml"
    - stage: Coding standard
      php: 7.4
      install: travis_retry composer install --prefer-dist
      script: vendor/bin/phpcs

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpunit $COVERAGE

after_script:
  - if [ "$COVERAGE" != "" ]; then vendor/bin/coveralls --verbose || true; fi

